# Generated by Django 4.1.2 on 2022-10-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_name', models.TextField()),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.TextField()),
                ('division', models.TextField()),
                ('stadium_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.TextField()),
                ('position', models.TextField()),
                ('player_age', models.IntegerField(null=True)),
                ('years_on_team', models.IntegerField(null=True)),
                ('games_started', models.IntegerField(null=True)),
                ('college', models.TextField()),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_team_points', models.IntegerField(null=True)),
                ('away_team_points', models.IntegerField(null=True)),
                ('away_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_away_team_id', to='app.teams', verbose_name='Away Team ID')),
                ('home_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_home_team_id', to='app.teams', verbose_name='Home Team ID')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast_Networks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('broadcast_company', models.CharField(max_length=64)),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.games')),
            ],
        ),
    ]
