# Generated by Django 4.1.2 on 2022-10-20 18:21

from django.db import migrations, models
import django.db.models.deletion
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.TextField()),
                ('stadium', models.TextField()),
                ('division', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(verbose_name=enum.unique)),
                ('player_name', models.TextField()),
                ('position', models.TextField()),
                ('p_weight', models.FloatField()),
                ('p_height', models.FloatField()),
                ('college', models.TextField()),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teams')),
            ],
        ),
    ]
