# Generated by Django 4.1.2 on 2022-10-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_name', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='players',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='stadium',
        ),
        migrations.AlterField(
            model_name='players',
            name='player_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('away_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_away_team_id', to='app.teams', verbose_name='Away Team ID')),
                ('home_team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_home_team_id', to='app.teams', verbose_name='Home Team ID')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast_Networks',
            fields=[
                ('broadcast_company', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.games')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='stadium_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stadium'),
        ),
    ]
