# Generated by Django 4.1.2 on 2022-10-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_games_game_date_remove_players_p_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
